### PR TITLE
Fix multiple definitions of trace macro

### LINKED ISSUE #346: Compiling with debug logs fails
When either of `NIGIRI_DIJKSTRA_TRACING` or `NIGIR_TRACING` is defined compilation fails because `trace` macro is defined multiple times (by `routing/dijkstra.cc` and `routing/raptor/debug.h`.

### PR DESCRIPTION
**Pull request by aff3npirat**
Fixes #346

### CODE REVIEW

File: include/nigiri/routing/raptor/debug.h [hunk 1]
```diff
@@ -11,9 +11,9 @@
 #define trace_upd(...) fmt::print(__VA_ARGS__)
 
 #ifdef NIGIRI_RAPTOR_TRACING_ONLY_UPDATES
-#define trace(...)
+#define trace_raptor(...)
```
Comment (felixguendling) [inline include/nigiri/routing/raptor/debug.h]: this can stay `trace` if `trace_dijkstra` gets changed?

File: include/nigiri/routing/raptor/raptor.h [hunk 2]
```diff
@@ -292,7 +292,7 @@ struct raptor {
       for (auto k = 1U; k != end_k; ++k) {
         auto const dest_time = round_times_[k][i][Vias];
         if (dest_time != kInvalid) {
-          trace("ADDING JOURNEY: start={}, dest={} @ {}, transfers={}\n",
+          trace_raptor("ADDING JOURNEY: start={}, dest={} @ {}, transfers={}\n",
```
Comment (felixguendling) [inline include/nigiri/routing/raptor/raptor.h]: please enable format-on-save

Comment (aff3npirat) [reply include/nigiri/routing/raptor/raptor.h]: I will, sorry that it happend so often...

File: include/nigiri/routing/raptor/debug.h (hunk 1 above)
Comment (aff3npirat) [reply include/nigiri/routing/raptor/debug.h]: Yes it can. I renamed it to avoid problems with other dependencies/projects using nigiri.
Should I rename it back?

Comment (felixguendling) [reply include/nigiri/routing/raptor/debug.h]: we can #undef the macro at the end of each header file using it
but actually this macro should ideally not leak as it's in an implementation file
maybe we can reorganize the code so other code does not depend on implementation details of the nigiri library

for now keep it `trace`

Comment (aff3npirat) [reply include/nigiri/routing/raptor/debug.h]: Ok will rename it.
I also thought of `#undef` but e.g. `trace_raptor` is used by other header files where it is not defined - so we would have to redefine the macro. I think if we can solve this issue by restructuring it would be much cleaner, and easier to keep track where each macro is used.

**Comment by aff3npirat** [comment]
The problem was an unused import of `rt_timetable.h (-> delta_t.h)`.
I removed the import and `delta_t` no longer depends on `debug.h` + added macros to enable/disable logging for other parts.

File: include/nigiri/common/delta_t.h [hunk 3]
```diff
@@ -1,7 +1,7 @@
 #pragma once
 
-#include "nigiri/routing/raptor/debug.h"
 #include "nigiri/types.h"
+#include "fmt/base.h"
```
Comment (felixguendling) [inline include/nigiri/common/delta_t.h:3]: header ordering (see STYLE.md)

File: src/loader/gtfs/seated.cc [hunk 4]
```diff
@@ -4,8 +4,12 @@
 
 #include <ranges>
 
-// #define trace(...) fmt::println(std::clog, __VA_ARGS__)
+// #define NIGIRI_SEATED_DEBUG
+#ifdef NIGIRI_SEATED_DEBUG
+#define trace(...) fmt::println(__VA_ARGS__)
+#else
 #define trace(...)
+#endif
```
Comment (felixguendling) [inline src/loader/gtfs/seated.cc]: what's wrong with having the simple one line solution?

File: src/routing/ontrip_train.cc [hunk 5]
```diff
@@ -5,16 +5,14 @@
 #include "nigiri/routing/query.h"
 #include "nigiri/timetable.h"
 
-namespace nigiri::routing {
-
-constexpr auto const kTracing = true;
+// #define NIGIRI_ONTRIP_DEBUG
```
Comment (felixguendling) [inline src/routing/ontrip_train.cc]: couldn't this also be `// #define trace(...) fmt::println(std::clog, __VA_ARGS__)`

File: src/loader/gtfs/seated.cc (hunk 4 above)
Comment (aff3npirat) [reply src/loader/gtfs/seated.cc]: I just thought it is more convenient to enable/disable logging by passing compiler flags than actually changing source code. This prevents forgetting to disable logging before commiting/pushing.

File: src/routing/ontrip_train.cc (hunk 5 above)
Comment (aff3npirat) [reply src/routing/ontrip_train.cc]: Yes, same reasoning for my implementation as in reply to
> what's wrong with having the simple one line solution?

File: src/loader/gtfs/seated.cc (hunk 4 above)
Comment (felixguendling) [reply src/loader/gtfs/seated.cc]: I don't think that's the approach people take. At least not me. Uncommenting one line of code is the most simple solution I can think of and not checking this change into Git is doable.

Comment (aff3npirat) [reply src/loader/gtfs/seated.cc]: Okay will do. Should I also change `fares.cc` to use a simple comment/uncomment approach (and maybe also `dijkstra.cc`) or simply leave everthing as is?

Comment (felixguendling) [reply src/loader/gtfs/seated.cc]: > Should I also change fares.cc to use a simple comment/uncomment approach (and maybe also dijkstra.cc)

yes

Comment (aff3npirat) [reply src/loader/gtfs/seated.cc]: Done. `fares.cc` couldnt be changed this way because `NIGIRI_FARES_DEBUG` macro actually changes code instead of only handling `trace` definition (see line 358).

Comment (felixguendling) [reply src/loader/gtfs/seated.cc]: let me know when it's ready for review
